// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _28_Example;

#nullable disable

namespace _28_Example.Migrations
{
    [DbContext(typeof(ExampleDbContext))]
    [Migration("20260507122534_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("_28_Example.Rechnung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ergebnis")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Op")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Zahl1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Zahl2")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Rechnungen");
                });
#pragma warning restore 612, 618
        }
    }
}
